name: Monitor Organization Commit Activity

on:
    push:
      branches:
        - main  # Trigger workflow on push events to the main branch
    workflow_dispatch:

jobs:
            monitor_commit_activity:
              runs-on: ubuntu-latest
          
              steps:
                - name: Fetch Organization Members
                  id: fetch_members
                  run: |
                    members=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
                              https://api.github.com/orgs/Nivesh-s-Learning/members | \
                              jq -r '.[].login')
                    echo "::set-output name=members::$members"
                  
                - name: Iterate Over Members and Get Latest Commit
                  id: iterate_members
                  run: |
                    members=(${{ steps.fetch_members.outputs.members }})
                    for member in "${members[@]}"; do
                      latest_commit=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
                                      "https://api.github.com/users/$member/events" | \
                                      jq -r 'map(select(.type=="PushEvent")) | .[0].created_at')
                      echo "Latest commit by $member: $latest_commit"
                      # Add logic to calculate time difference and send email notification based on your requirements
                    done