name: Monitor Organization Commit Activity

on:
  push:
    branches:
      - main # Trigger workflow on push events to the main branch
  workflow_dispatch:

jobs:
  monitor_commit_activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Static List of Members
        id: set_members
        run: |
          members=(anantsinghal47 mitul-garg Nivesh108 Samarthsharma9) # Replace with actual member usernames
          echo "MEMBERS=${members[*]}" >> $GITHUB_ENV

      - name: Iterate Over Repositories and Branches
        id: iterate_repos
        run: |
          repos=(Email_Notifications mitul-testing)
          members=($MEMBERS)
          echo "Repositories to iterate: ${repos[@]}"
          echo "Members to check: ${members[@]}"

          current_time=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          one_day_ago=$(date -u -d "24 hours ago" +%Y-%m-%dT%H:%M:%SZ)
          echo "Current time: $current_time"
          echo "One day ago: $one_day_ago"

          for repo in "${repos[@]}"; do
            echo "$ Current repo: $repo"
            page=1
            while true; do
              url="https://api.github.com/repos/Nivesh-s-Learning/$repo/branches?page=$page&per_page=100"
              response=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" "$url")

              if [[ "$response" == *"404 Not Found"* ]]; then
                echo "Error: Repository $repo not found or authentication issue. Check if the repository name is correct and the token has access."
                break
              fi

              if [[ "$response" == "[]" ]]; then
                echo "No branches found for repository: $repo"
                break
              fi

              branches=$(echo "$response" | jq -r '.[].name' || echo "[]")
              if [[ -z "$branches" || "$branches" == "[]" ]]; then
                echo "No branches found for repository: $repo"
                break
              fi

              for branch in $branches; do
                echo "Current branch: $branch"
                commit_page=1
                while true; do
                  url="https://api.github.com/repos/Nivesh-s-Learning/$repo/commits?sha=$branch&since=$one_day_ago&page=$commit_page&per_page=100"
                  response=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" "$url")
                  
                  
                  if [[ -z "$response" || "$response" == "[]" ]]; then
                    echo "No commits found for branch: $branch"
                    break
                  fi
                  
                  commits=$(echo "$response" | jq -c '.[]' || echo "[]")
                  if [[ -z "$commits" || "$commits" == "[]" ]]; then
                    break
                  fi
                  
                  for commit in "${commits[@]}"; do
                    echo "$commit"
                    author=$(echo $commit | jq -r '.author.login')
                    echo "Author: $author"
                    echo "AUthor log"
                    if [[ -n "$author" && " ${members[@]} " =~ " ${author} " ]]; then
                      echo "Commit found for $author in $repo/$branch"
                      echo "Previous List: ${members[@]}"
                      # Remove member from the array if commit found
                      members=(${members[@]/$author})
                      echo "List after removing $author : ${members[@]}"
                    fi
                   
                  done
                  ((commit_page++))
                done
              done
              ((page++))
            done
          done

          echo "INACTIVE_MEMBERS=${members[*]}" >> $GITHUB_ENV

      - name: Fetch Email IDs for Members
        id: fetch_emails
        run: |
          inactive_members=($INACTIVE_MEMBERS)
          echo "$inactive_members"
          emails=()
          for member in "${inactive_members[@]}"; do
            response=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
              "https://api.github.com/users/$member")
            email=$(echo "$response" | jq -r '.email')
            if [ "$email" != "null" ]; then
              emails+=("$email")
            else
              echo "Email not found for user: $member"
            fi
          done
          EMAILS=$(IFS=, ; echo "${emails[*]}")
          echo "EMAILS=$EMAILS" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Send Email Notifications
        run: |
          echo "Sending emails to: $EMAILS"
          python send_email.py
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAILS: ${{ env.EMAILS }}
