name: Monitor Organization Commit Activity

on:
    push:
      branches:
        - main  # Trigger workflow on push events to the main branch
    workflow_dispatch:

jobs:
            monitor_commit_activity:
              runs-on: ubuntu-latest
          
              steps:
                - name: Send Email Notifications
                  uses: dawidd6/action-send-mail@v3
                  with:
                    server_address: smtp.google.com
                    server_port: 587
                    username: ${{ secrets.SMTP_USERNAME }}
                    password: ${{ secrets.SMTP_PASSWORD }}
                    subject: "Test Mail"
                    to: mitulgarg2000@gmail.com
                    from: sharmanivesh08@gmail.com
                    body: |
                        Did you get this mail?                    
