name: Monitor Organization Commit Activity

on:
    push:
      branches:
        - main  # Trigger workflow on push events to the main branch
    workflow_dispatch:

jobs:
            monitor_commit_activity:
              runs-on: ubuntu-latest
          
              steps:
                - name: Fetch Organization Members
                  id: fetch_members
                  run: |
                    members=()
                    page=1
                    while true; do
                      response=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
                                 "https://api.github.com/orgs/Nivesh-s-Learning/members?page=$page&per_page=100")
                      current_members=$(echo "$response" | jq -r '.[].login')
                      members+=($current_members)
                      if [[ -z $current_members ]]; then
                        break
                      fi
                      ((page++))
                    done
                    echo "::set-output name=members::${members[@]}"
                  
                - name: Iterate Over Members and Get Latest Commit
                  id: iterate_members
                  run: |
                    members=(${{ steps.fetch_members.outputs.members }})
                    for member in "${members[@]}"; do
                      latest_commit=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
                                      "https://api.github.com/users/$member/events" | \
                                      jq -r 'map(select(.type=="PushEvent")) | .[0].created_at')
                      echo "Latest commit by $member: $latest_commit"
                      # Add logic to calculate time difference and send email notification based on your requirements

                - name: Fetch Email IDs for Members
                  id: fetch_emails
                  run: |
                    members=(${{ steps.fetch_members.outputs.members }})
                    emails=()
                    for member in "${members[@]}"; do
                      email=$(curl -s -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
                            "https://api.github.com/users/$member" | \
                            jq -r '.email')
                    emails+=($email)
                    done
                    echo "::set-output name=emails::${emails[@]}"

                # - name: Send Email if Latest commit not has happened in last 24 hours
                #   uses: dawidd6/action-send-mail@v3
                #   with:
                #     server_address: smtp.gmail.com 
                #     server_port: 587  
                #     username: ${{ secrets.SMTP_USERNAME }}  
                #     password: ${{ secrets.SMTP_PASSWORD }}
                #     from: sharmanivesh08@gmail.com
                #     subject: "Latest Commit Info"
                #     body: "There have been no commits in the last 1 minute."
                #     to: niveshtnp@gmail.com
                        
                #         done